### ISSUE TITLE
Issue with manually inputting data into the checklist

### ISSUE THREAD

**Issue by stigsfoot** [nditech/dev-elections#131]
From Ben: 
This might be based on a misunderstanding of how manually inputting data into apollo works, so will review at our weekly meeting, but there appears to be an issue with manually inputting data into the checklist. There is a disconnect between whether the green checkmark shows up and whether the pie chart is filled. If data is manually put in, it is also not always overwritten when a phone sends in a message.

Aha! Link: https://nditech.aha.io/features/APOLLO-119

**Comment by blynchNDI** [comment]
Confirming this has been resolved
