### ISSUE TITLE
exploring form sections on the dashboard shows data for the admin level but cannot be explored further

### ISSUE THREAD

**Issue by takinbo** [nditech/dev-elections#141]
When a user is exploring data on the dashboard, they should be able to explore the data at all the enabled administrative divisions, currently, they are only able to explore the data at the topmost enabled admin division, the link to go further is not enabled.

![screenshot-1549042023](https://user-images.githubusercontent.com/41004/52139121-1f3aee00-2647-11e9-976e-9b1be96ae658.png)

**Comment by blynchNDI** [comment]
Confirmed as fixed
