### ISSUE TITLE
move from "form sets" to just "forms"

### ISSUE THREAD

**Issue by takinbo** [nditech/dev-elections#165]
There has been some confusion about the workflow of how events are set up using forms. Rather than having _form sets_ where you unnecessarily group forms into _sets_, we would simply just define all the forms as just _forms_ and then select which forms will be used in an event during the event creation itself or modification.

Also, due to the possibility of having a large number of forms, there should be a forms search interface so forms can be found quickly.

Aha! Link: https://nditech.aha.io/features/APOLLO-192

**Comment by blynchNDI** [comment]
@SarahCooperNDI @sarahmoulton flagging this, as the 'form set' to 'forms' fix was implemented, but there is no search function for forms, as mentioned in the description for this issue. Is this something important that we should open a separate issue for?
