### ISSUE TITLE
ensure that site meets standard accessibility requirements

### ISSUE THREAD

**Issue by takinbo** [nditech/dev-elections#181]
@sarahmoulton could you provide some guidance?

Aha! Link: https://nditech.aha.io/features/APOLLO-182

**Comment by blynchNDI** [comment]
@sarahmoulton we should discuss this further to see if more is needed here

**Comment by takinbo** [comment]
We are currently getting between 96 and 98% in accessibility tests from Lighthouse. We made some changes to improve contrast but not by a lot. At this stage, it will only yield minimal improvements vs the amount of work that would be done to improve colour contrasts; as a result, we are not going to do further optimisations.
