### ISSUE TITLE
Order Admin Divisions in order on the upload 

### ISSUE THREAD

**Issue by blynchNDI** [nditech/dev-elections#547]
Currently, the admin divisions sometimes appear out of order on the mapping page for uploading a location set. It would be easier if the divisions were always in the order of hierarchy on the dropdown menus for location uploading.  

Pull request #538 may already fix this.

**Comment by blynchNDI** [comment]
just fyi, another place I noticed this is on the dropdown menu for location when creating checklists

**Comment by takinbo** [comment]
should be resolved in #538

**Comment by blynchNDI** [comment]
Looks good on initial test, will test further to confirm

**Comment by blynchNDI** [comment]
Tested and was not able to reproduce it. Will reopen if I do see the issue come up again
